In [ ]:
#scratch EDA based on Mike's initial scan of crash data
#TODO - get data dictionary downloaded
#TODO - document our website filters for current CSV     - (or data cleaning)

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
av = pd.read_csv('../datasets/aviation_data.csv')

In [3]:
pd.set_option('display.max_columns', None) 
pd.set_option('display.max_colwidth', None)

In [4]:
av.head()

,NtsbNo,EventType,Mkey,EventDate,City,State,Country,ReportNo,N,HasSafetyRec,ReportType,OriginalPublishDate,HighestInjuryLevel,FatalInjuryCount,SeriousInjuryCount,MinorInjuryCount,ProbableCause,EventID,Latitude,Longitude,Make,Model,AirCraftCategory,AirportID,AirportName,AmateurBuilt,NumberOfEngines,Scheduled,PurposeOfFlight,FAR,AirCraftDamage,WeatherCondition,Operator,ReportStatus,RepGenFlag,DocketUrl,DocketPublishDate,Unnamed: 37
0,ERA24LA019,ACC,193301,2023-10-25T09:57:00Z,Atlanta,Georgia,United States,NaN,N7981E,False,DirectorBrief,NaN,NaN,0,0,0,NaN,NaN,0.0,0.0,CESSNA,150,AIR,CCO,Newnan Coweta County Airport,FALSE,1,NaN,INST,091,NaN,VMC,NaN,In work,False,NaN,NaN,NaN
1,CEN24LA020,ACC,193291,2023-10-23T15:11:00Z,Pierre,South Dakota,United States,NaN,N92884,False,DirectorBrief,NaN,Fatal,1,1,0,NaN,NaN,0.0,0.0,PIPER,PA 46-350P,NaN,NaN,NaN,FALSE,NaN,NaN,PERS,091,NaN,NaN,NaN,In work,False,NaN,NaN,NaN
2,CEN24LA023,ACC,193305,2023-10-22T19:00:00Z,Union charter Township,Michigan,United States,NaN,N8088E,False,DirectorBrief,NaN,NaN,0,0,0,NaN,NaN,0.0,0.0,PIPER,PA-28-201T,NaN,NaN,NaN,FALSE,NaN,NaN,PERS,091,NaN,NaN,NaN,In work,False,NaN,NaN,NaN
3,WPR24FA018,ACC,193276,2023-10-20T17:01:00Z,Covelo,California,United States,NaN,N8248K,False,DirectorBrief,NaN,Fatal,2,0,0,NaN,NaN,0.0,0.0,BEECH,A36,NaN,NaN,NaN,FALSE,NaN,NaN,PERS,091,NaN,NaN,PLANE HAVEN LLC,In work,False,NaN,NaN,NaN
4,ERA24LA015,ACC,193282,2023-10-20T16:00:00Z,Tellico Plains,Tennessee,United States,NaN,N958TW,False,DirectorBrief,NaN,NaN,0,0,0,NaN,NaN,0.0,0.0,AVIAT AIRCRAFT INC,A-1C-200,AIR,NONE,NaN,FALSE,1,NaN,PERS,091,NaN,VMC,NaN,In work,False,NaN,NaN,NaN

In [5]:
av.shape

(89505, 38)

In [6]:
av.describe()

,Mkey,FatalInjuryCount,SeriousInjuryCount,MinorInjuryCount,EventID,Latitude,Longitude,Unnamed: 37
count,89505.000000,89505.000000,89505.000000,89505.000000,0.0,8.950500e+04,8.950500e+04,0.0
mean,52721.064209,0.547355,0.212256,0.338931,NaN,1.285408e+03,-7.657945e+01,NaN
std,33341.346545,4.902895,1.090214,2.307135,NaN,2.182867e+05,8.431713e+03,NaN
min,2292.000000,0.000000,0.000000,0.000000,NaN,-7.801694e+01,-1.004241e+06,NaN
25%,25031.000000,0.000000,0.000000,0.000000,NaN,2.986805e+01,-1.119175e+02,NaN
50%,50203.000000,0.000000,0.000000,0.000000,NaN,3.622666e+01,-9.064059e+01,NaN
75%,75937.000000,0.000000,0.000000,0.000000,NaN,4.159992e+01,-7.785972e+01,NaN
max,193305.000000,349.000000,111.000000,380.000000,NaN,4.351118e+07,7.457204e+05,NaN

In [10]:
av.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89505 entries, 0 to 89504
Data columns (total 38 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   NtsbNo               89505 non-null  object
 1   EventType            89505 non-null  object
 2   Mkey                 89505 non-null  int64
 3   EventDate            89505 non-null  object
 4   City                 89444 non-null  object
 5   State                82309 non-null  object
 6   Country              89008 non-null  object
 7   ReportNo             216 non-null    object
 8   N                    89408 non-null  object
 9   HasSafetyRec         89505 non-null  bool
 10  ReportType           82887 non-null  object
 11  OriginalPublishDate  70460 non-null  object
 12  HighestInjuryLevel   40706 non-null  object
 13  FatalInjuryCount     89505 non-null  int64
 14  SeriousInjuryCount   89505 non-null  int64
 15  MinorInjuryCount     89505 non-null  int64
 16  ProbableCause        60382 non-null  object
 17  EventID              0 non-null      float64
 18  Latitude             89505 non-null  float64
 19  Longitude            89505 non-null  float64
 20  Make                 89443 non-null  object
 21  Model                89416 non-null  object
 22  AirCraftCategory     88864 non-null  object
 23  AirportID            50420 non-null  object
 24  AirportName          53001 non-null  object
 25  AmateurBuilt         89505 non-null  object
 26  NumberOfEngines      83447 non-null  object
 27  Scheduled            12739 non-null  object
 28  PurposeOfFlight      83133 non-null  object
 29  FAR                  88822 non-null  object
 30  AirCraftDamage       86213 non-null  object
 31  WeatherCondition     84688 non-null  object
 32  Operator             43740 non-null  object
 33  ReportStatus         83034 non-null  object
 34  RepGenFlag           89505 non-null  bool
 35  DocketUrl            22081 non-null  object
 36  DocketPublishDate    22081 non-null  object
 37  Unnamed: 37          0 non-null      float64
dtypes: bool(2), float64(4), int64(4), object(28)
memory usage: 24.8+ MB

In [7]:
av.select_dtypes(exclude = np.number).describe()

,NtsbNo,EventType,EventDate,City,State,Country,ReportNo,N,HasSafetyRec,ReportType,OriginalPublishDate,HighestInjuryLevel,ProbableCause,Make,Model,AirCraftCategory,AirportID,AirportName,AmateurBuilt,NumberOfEngines,Scheduled,PurposeOfFlight,FAR,AirCraftDamage,WeatherCondition,Operator,ReportStatus,RepGenFlag,DocketUrl,DocketPublishDate
count,89505,89505,89505,89444,82309,89008,216,89408,89505,82887,70460,40706,60382,89443,89416,88864,50420,53001,89505,83447,12739,83133,88822,86213,84688,43740,83034,89505,22081,22081
unique,89505,3,87383,22486,57,189,214,81074,2,3,2187,3,56803,9173,13511,40,10533,25341,7,39,3,130,81,29,3,37702,2,1,22081,19012
top,ERA24LA019,ACC,1987-12-10T10:30:00Z,ANCHORAGE,California,United States,AAR8903,UNREG,False,DirectorBrief,2020-11-03T05:00:00Z,Fatal,A loss of engine power for undetermined reasons.,CESSNA,152,AIR,NONE,Private,FALSE,1,NSCH,PERS,091,Substantial,VMC,",",Completed,False,https://data.ntsb.gov/Docket?ProjectID=193042,10/9/2020 5:40:27 PM
freq,1,85540,4,361,8795,82429,2,521,88843,82690,1046,17809,124,18498,2273,76092,1489,249,79934,69233,4645,49217,70270,64154,77626,480,81839,89505,1,44

In [8]:
av['N'].value_counts()

N
UNREG      521
UNK         39
NONE        10
N20752       8
unknown      7
          ...
N421XJ       1
N370RL       1
N5537F       1
N8947K       1
N5069P       1
Name: count, Length: 81074, dtype: int64

In [9]:
av.loc[av['N'] == 'N20752', 'ProbableCause'].to_frame()

                                                                                                                                                                                                                                                  ProbableCause
41155                                                                                                                            The pilot's selection of unsuitable terrain for landing.  A factor in the accident was a hidden obstruction, and soft terrain.
47567  the pilot's inadequate compensation for wind conditions, and his failure to maintain directional control of the airplane, which resulted in a ground swerve and damage to the airplane.  A factor relating to the accident was: the crosswind condition.
49865                                                                                                                                                                                  The pilot's excessive application of the brakes during the landing roll.
53803                                                                                               A FAILURE OF THE PILOT TO MAINTAIN ADEQUATE DISTANCE FROM THE TERRAIN (SNOW BANK).  FLAT LIGHTING AND LOW CONTRAST CONDITIONS WERE FACTORS IN THE ACCIDENT.
56472                                                            FUEL EXHAUSTION AS A RESULT OF THE PILOT IN COMMAND'S NOT REFUELING. A FACTOR IN THE ACCIDENT WAS THE OPERATOR/MANAGEMENT INADEQUATE FLIGHT FOLLOWING AND OPERATIONAL CONTROL OVER THE FLIGHT.
58114       THE FAILURE OF THE NO. TWO CYLINDER CONNECTING ROD DUE TO A SLIPPED (SPUN) MAIN CRANKSHAFT BEARING WHICH BLOCKED OFF THE OIL HOLE TO THE CONNECTING ROD.  A FACTOR IN THE ACCIDENT WAS THE UNSUITABLE TERRAIN ON WHICH TO PERFORM A FORCED LANDING.
59658                                                                                                 THE IMPROPER USE OF THE FLT CONTROLS BY THE SECOND PILOT DURING LANDING ROLL.  FACTORS RELATING TO THE MISHAP WERE THE ROUGH/UNEVEN SNOW COVERED TERRAIN.
67874                                                                                                                                                                                                                                                       NaN