In [1]:
import pandas as pd

In [2]:
c02 = pd.read_csv('../datasets/airtrans_c02.csv')

/var/folders/q7/5h2c80n91kv48jr01119s4t80000gn/T/ipykernel_21536/856862369.py:1: DtypeWarning: Columns (14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  c02 = pd.read_csv('../datasets/airtrans_c02.csv')

In [32]:
c02.shape

(334593, 19)

In [3]:
c02.head()

,LOCATION,Country,POLLUTANT,Pollutant,MEASURE,Measure,FLIGHT,Flight type,FREQUENCY,Frequency,SOURCE,Source of emissions,SEASONALITY,Seasonality,TIME,Time,Value,Flag Codes,Flags
0,AUS,Australia,CO2,Carbon dioxide,TCO2,tonnes of CO2-equivalent,TOTAL,All flights,A,Annual,RES_DOM_IN,"""(A) - Domestic flight in country A, operated ...",NSA,Non seasonally adjusted,2015,2015,7.351698e+06,NaN,NaN
1,AUS,Australia,CO2,Carbon dioxide,TCO2,tonnes of CO2-equivalent,TOTAL,All flights,A,Annual,RES_DOM_IN,"""(A) - Domestic flight in country A, operated ...",NSA,Non seasonally adjusted,2016,2016,7.415273e+06,NaN,NaN
2,AUS,Australia,CO2,Carbon dioxide,TCO2,tonnes of CO2-equivalent,TOTAL,All flights,A,Annual,RES_DOM_IN,"""(A) - Domestic flight in country A, operated ...",NSA,Non seasonally adjusted,2017,2017,7.333902e+06,NaN,NaN
3,AUS,Australia,CO2,Carbon dioxide,TCO2,tonnes of CO2-equivalent,TOTAL,All flights,A,Annual,RES_DOM_IN,"""(A) - Domestic flight in country A, operated ...",NSA,Non seasonally adjusted,2018,2018,7.320473e+06,NaN,NaN
4,AUS,Australia,CO2,Carbon dioxide,TCO2,tonnes of CO2-equivalent,TOTAL,All flights,A,Annual,RES_DOM_IN,"""(A) - Domestic flight in country A, operated ...",NSA,Non seasonally adjusted,2019,2019,7.753970e+06,NaN,NaN

In [4]:
c02.tail()

,LOCATION,Country,POLLUTANT,Pollutant,MEASURE,Measure,FLIGHT,Flight type,FREQUENCY,Frequency,SOURCE,Source of emissions,SEASONALITY,Seasonality,TIME,Time,Value,Flag Codes,Flags
334588,GEO,Georgia,CO2,Carbon dioxide,TCO2,tonnes of CO2-equivalent,C,Freight flights,M,Monthly,RES_INT_OUT,"""(F) - International flight outside of country...",NSA,Non seasonally adjusted,2023-06,Jun-2023,8.41529,NaN,NaN
334589,GEO,Georgia,CO2,Carbon dioxide,TCO2,tonnes of CO2-equivalent,C,Freight flights,M,Monthly,RES_TOTAL,Air transport - Industry H51 (ISIC rev.4): (A)...,NSA,Non seasonally adjusted,2023-06,Jun-2023,8.41529,NaN,NaN
334590,GEO,Georgia,CO2,Carbon dioxide,TCO2,tonnes of CO2-equivalent,C,Freight flights,M,Monthly,RES_ABROAD,Bridging item - Residents abroad: (B)+(D)+(E)+(F),NSA,Non seasonally adjusted,2023-06,Jun-2023,8.41529,NaN,NaN
334591,MHL,Marshall Islands,CO2,Carbon dioxide,TCO2,tonnes of CO2-equivalent,C,Freight flights,M,Monthly,NRES_INT_FROM,"""(G) - International flight departing from cou...",NSA,Non seasonally adjusted,2023-06,Jun-2023,35.29190,NaN,NaN
334592,MHL,Marshall Islands,CO2,Carbon dioxide,TCO2,tonnes of CO2-equivalent,C,Freight flights,M,Monthly,TER_INT,International aviation (memo item): (D)+(G),NSA,Non seasonally adjusted,2023-06,Jun-2023,35.29190,NaN,NaN

In [5]:
c02.dtypes

LOCATION                object
Country                 object
POLLUTANT               object
Pollutant               object
MEASURE                 object
Measure                 object
FLIGHT                  object
Flight type             object
FREQUENCY               object
Frequency               object
SOURCE                  object
Source of emissions     object
SEASONALITY             object
Seasonality             object
TIME                    object
Time                    object
Value                  float64
Flag Codes             float64
Flags                  float64
dtype: object

In [14]:
c02['SOURCE'].value_counts()

SOURCE
TER_INT          39640
NRES_INT_FROM    39078
RES_TOTAL        31346
RES_ABROAD       30452
RES_INT_OUT      26418
RES_DOM_OUT      26339
RES_INT_TO       26302
RES_INT_FROM     26157
TER_DOM          25702
RES_DOM_IN       22071
NRES_DOM_IN      20544
NRES_TERR        20544
Name: count, dtype: int64

In [6]:
c02['Source of emissions'].value_counts()

Source of emissions
International aviation (memo item): (D)+(G)                                                                        39640
"(G) - International flight departing from country A, operated by an airline that is non-resident in country A"    39078
Air transport - Industry H51 (ISIC rev.4): (A)+(B)+(D)+(E)+(F)                                                     31346
Bridging item - Residents abroad: (B)+(D)+(E)+(F)                                                                  30452
"(F) - International flight outside of country A, operated by a resident airline of country A"                     26418
"(B) - Domestic flight outside of country A, operated by a resident airline of country A"                          26339
"(E) - International flight arriving in country A, operated by a resident airline of country A"                    26302
"(D) - International flight departing from country A, operated by a resident airline of country A"                 26157
Domestic aviation: (A)+(C)                                                                                         25702
"(A) - Domestic flight in country A, operated by a resident airline of country A"                                  22071
"(C) - Domestic flight in country A, operated by an airline that is non-resident in country A"                     20544
Bridging item - Non-residents on territory: (C)                                                                    20544
Name: count, dtype: int64

In [27]:
c02_ter = c02[(c02['SOURCE'] == 'TER_INT') | (c02['SOURCE'] == 'TER_DOM')]

In [24]:
c02_ter.tail()

,LOCATION,Country,POLLUTANT,Pollutant,MEASURE,Measure,FLIGHT,Flight type,FREQUENCY,Frequency,SOURCE,Source of emissions,SEASONALITY,Seasonality,TIME,Time,Value,Flag Codes,Flags
334576,ALB,Albania,CO2,Carbon dioxide,TCO2,tonnes of CO2-equivalent,P,Passenger flights,M,Monthly,TER_DOM,Domestic aviation: (A)+(C),NSA,Non seasonally adjusted,2023-05,May-2023,14.98480,NaN,NaN
334580,BIH,Bosnia and Herzegovina,CO2,Carbon dioxide,TCO2,tonnes of CO2-equivalent,C,Freight flights,Q,Quarterly,TER_INT,International aviation (memo item): (D)+(G),NSA,Non seasonally adjusted,2023-Q2,Q2-2023,9.18504,NaN,NaN
334585,MHL,Marshall Islands,CO2,Carbon dioxide,TCO2,tonnes of CO2-equivalent,C,Freight flights,Q,Quarterly,TER_INT,International aviation (memo item): (D)+(G),NSA,Non seasonally adjusted,2023-Q2,Q2-2023,35.29190,NaN,NaN
334587,BIH,Bosnia and Herzegovina,CO2,Carbon dioxide,TCO2,tonnes of CO2-equivalent,C,Freight flights,M,Monthly,TER_INT,International aviation (memo item): (D)+(G),NSA,Non seasonally adjusted,2023-06,Jun-2023,9.18504,NaN,NaN
334592,MHL,Marshall Islands,CO2,Carbon dioxide,TCO2,tonnes of CO2-equivalent,C,Freight flights,M,Monthly,TER_INT,International aviation (memo item): (D)+(G),NSA,Non seasonally adjusted,2023-06,Jun-2023,35.29190,NaN,NaN

In [25]:
c02_ter.head()

,LOCATION,Country,POLLUTANT,Pollutant,MEASURE,Measure,FLIGHT,Flight type,FREQUENCY,Frequency,SOURCE,Source of emissions,SEASONALITY,Seasonality,TIME,Time,Value,Flag Codes,Flags
80,AUS,Australia,CO2,Carbon dioxide,TCO2,tonnes of CO2-equivalent,TOTAL,All flights,A,Annual,TER_DOM,Domestic aviation: (A)+(C),NSA,Non seasonally adjusted,2015,2015,7.395764e+06,NaN,NaN
81,AUS,Australia,CO2,Carbon dioxide,TCO2,tonnes of CO2-equivalent,TOTAL,All flights,A,Annual,TER_DOM,Domestic aviation: (A)+(C),NSA,Non seasonally adjusted,2016,2016,7.463633e+06,NaN,NaN
82,AUS,Australia,CO2,Carbon dioxide,TCO2,tonnes of CO2-equivalent,TOTAL,All flights,A,Annual,TER_DOM,Domestic aviation: (A)+(C),NSA,Non seasonally adjusted,2017,2017,7.386456e+06,NaN,NaN
83,AUS,Australia,CO2,Carbon dioxide,TCO2,tonnes of CO2-equivalent,TOTAL,All flights,A,Annual,TER_DOM,Domestic aviation: (A)+(C),NSA,Non seasonally adjusted,2018,2018,7.375074e+06,NaN,NaN
84,AUS,Australia,CO2,Carbon dioxide,TCO2,tonnes of CO2-equivalent,TOTAL,All flights,A,Annual,TER_DOM,Domestic aviation: (A)+(C),NSA,Non seasonally adjusted,2019,2019,7.960830e+06,NaN,NaN

In [26]:
c02_ter['Source of emissions'].value_counts()

Source of emissions
International aviation (memo item): (D)+(G)    39640
Domestic aviation: (A)+(C)                     25702
Name: count, dtype: int64

In [31]:
c02_ter.shape

(65342, 19)

In [29]:
c02_ter.to_csv('../datasets/territory_principle.csv', index=False)